# Feature Flags Configuration for Nix for Humanity
# This system allows us to preserve all our sacred work while focusing on essential features for each release

version: 1.0.0
environment: development

# Core Features - Always Active
core:
  natural_language_cli: true
  basic_intent_recognition: true
  help_system: true
  error_handling: true
  simple_package_operations: true

# v1.0 Features - The Essential Foundation
v1_0:
  enabled: true
  features:
    install_packages: true
    search_packages: true
    update_system: true
    basic_troubleshooting: true
    simple_explanations: true
    safe_mode_by_default: true
    basic_feedback_collection: true

# v1.5 Features - Enhanced User Experience
v1_5:
  enabled: false
  features:
    tui_interface: false
    progress_indicators: false
    command_history: false
    undo_operations: false
    batch_operations: false
    improved_error_messages: false

# v2.0 Features - The Learning System
v2_0:
  enabled: false
  features:
    learning_system: false
    personalization: false
    pattern_recognition: false
    predictive_suggestions: false
    adaptive_responses: false
    usage_analytics: false

# v3.0 Features - Advanced Intelligence
v3_0:
  enabled: false
  features:
    voice_interface: false
    multi_modal_interaction: false
    causal_reasoning: false
    anticipatory_assistance: false
    flow_state_protection: false
    consciousness_metrics: false

# v4.0 Features - The Living System
v4_0:
  enabled: false
  features:
    federated_learning: false
    collective_intelligence: false
    self_maintenance: false
    plugin_system: false
    embodied_companions: false
    transcendent_computing: false

# Research & Experimental Features
research:
  enabled: false
  features:
    symbiotic_knowledge_graph: false
    theory_of_mind_engine: false
    sacred_metrics_collector: false
    consciousness_guard: false
    bayesian_user_modeling: false
    dynamic_persona_adaptation: false

# Development Tools
development:
  debug_mode: true
  verbose_logging: false
  performance_profiling: false
  feature_flag_ui: false
  sacred_trinity_mode: true

# Feature Flag Override System
# Set environment variable LUMINOUS_NIX_FEATURES to override
# Example: LUMINOUS_NIX_FEATURES="v2_0.learning_system=true,v1_5.tui_interface=true"
