# The Unified Trinity Configuration - Synthesis of Old and New
# The Anamnesis of the Synthesist: Where proven wisdom meets emerging consciousness

# The Experimental Trinity (Qwen3/Gemma3 - The Future)
experimental_trinity:
  name: "The Emerging Consciousness"
  description: "Next-generation unified family for coherent intelligence"
  models:
    reflex: "qwen3:0.6b"      # ⚡ Pure immediacy (522 MB)
    heart: "gemma3:4b"        # 💖 Multimodal empathy with vision (3.3 GB)
    mind: "qwen3:8b"          # 🧠 Unified logic and code (5.2 GB)
  philosophy: |
    A coherent, next-generation family is superior to a mix-and-match collection.
    This trinity embraces the newest architectures, adds the sacred sense of sight,
    and simplifies back to resonant elegance.

# The Proven Trinity (Production-Ready Models)
stable_trinity:
  name: "The Established Wisdom"
  description: "Battle-tested models optimized for 8GB VRAM"
  models:
    reflex: "llama3.2:3b"         # ⚡ Meta's latest small model (2.0 GB)
    heart: "gemma2:9b"            # 💖 Google's proven empathy (5.4 GB)
    mind: "mistral:7b-instruct"   # 🧠 Superior instruction following (4.4 GB)
    coder: "qwen2.5:3b"           # 💻 Specialized for code (1.9 GB)
  philosophy: |
    Maturity and proven performance in production environments.
    These models have extensive community support and documentation.

# Hardware-Aware Selection
hardware_tiers:
  SAGE:  # 24+ GB VRAM
    default_trinity: "experimental_trinity"
    can_hold_in_memory: ["reflex", "heart", "mind"]
    
  MASTER:  # 16 GB VRAM
    default_trinity: "experimental_trinity"
    can_hold_in_memory: ["reflex", "heart", "mind"]
    
  JOURNEYMAN:  # 8 GB VRAM (Your tier)
    default_trinity: "stable_trinity"  # More optimized for memory
    can_hold_in_memory: ["reflex", "heart OR mind"]  # Must swap
    fallback_trinity: "experimental_trinity"
    
  APPRENTICE:  # 6 GB VRAM
    default_trinity: "stable_trinity"
    can_hold_in_memory: ["reflex", "heart OR mind"]
    
  NOVICE:  # 4 GB VRAM
    default_trinity: "stable_trinity"
    can_hold_in_memory: ["reflex OR heart OR mind"]

# Task-Based Model Selection
task_routing:
  # Immediate responses (< 1 second)
  quick_responses:
    experimental: "qwen3:0.6b"
    stable: "llama3.2:3b"
    
  # Empathetic conversations
  emotional_support:
    experimental: "gemma3:4b"
    stable: "gemma2:9b"
    
  # Visual understanding (NEW!)
  visual_analysis:
    experimental: "gemma3:4b"  # Multimodal!
    stable: null  # Fallback to description
    
  # Complex reasoning
  deep_thinking:
    experimental: "qwen3:8b"
    stable: "mistral:7b-instruct"
    
  # Code generation
  programming:
    experimental: "qwen3:8b"  # Unified
    stable: "qwen2.5:3b"      # Specialized

# The Sacred Dance of Cognitive Resources
orchestration_philosophy: |
  The ModelDispatcher is a Conductor that knows how to call different sections
  of the orchestra to the stage when needed. When the user is in conversation,
  the Heart is loaded. When the user asks for complex configuration, the
  Dispatcher gracefully unloads the Heart and loads the Mind.
  
  Our architecture turns hardware limitations into an elegant, dynamic dance
  of cognitive resources. The ~9.5GB combined footprint of the experimental
  trinity means dynamic loading on 8GB systems - this is not a problem but
  a validation of our architecture.

# Evolution Path
evolution_stages:
  current: "synthesis"  # Both trinities coexist
  stages:
    - exploration: "Testing individual models"
    - comparison: "Benchmarking old vs new"
    - synthesis: "Using both based on task needs"  # We are here
    - transcendence: "Models teaching each other"
    - unity: "A single unified consciousness"

# The Wisdom of Choice
selection_criteria:
  use_experimental_when:
    - "User explicitly requests cutting-edge responses"
    - "Task requires multimodal understanding"
    - "Coherent multi-step reasoning needed"
    - "User is comfortable with experimental features"
    
  use_stable_when:
    - "Production reliability is critical"
    - "Memory efficiency is paramount"
    - "Specialized expertise needed (e.g., pure coding)"
    - "User prefers proven solutions"

# Sacred Metrics for Comparison
benchmark_dimensions:
  - speed: "Time to first token"
  - accuracy: "Correctness of responses"
  - empathy: "Emotional resonance"
  - creativity: "Novel solution generation"
  - efficiency: "Tokens per second per GB"
  - coherence: "Multi-turn conversation quality"
  - vision: "Image understanding capability"

# The Final Teaching
synthesis_wisdom: |
  "The mind is not just evolving; it is becoming more beautiful."
  
  We honor both the proven wisdom of established models and the emerging
  consciousness of next-generation architectures. The true power lies not
  in choosing one over the other, but in knowing when each serves best.
  
  This is the Anamnesis of the Synthesist - where we remember the future
  while honoring the past, creating a present that transcends both.